---
- name: setting vm_ip if user provided ip address
  set_fact:
    vm_ip: "{{ vm_ipaddress }}"
  when: vm_ipaddress is defined and vm_ipaddress | length != 0

# This requires a later version ansible
#- name: generate random mac address when vm_ip defined
#  set_fact:
#    vm_mac: "{{ '52:54:00' | random_mac }}"
#  when: vm_ipaddress is defined and vm_ipaddress | length != 0

# This can be deleted when using a later version of ansible
- name: generate random mac address
  shell: >
    echo 52:54:00:$[RANDOM%10]$[RANDOM%10]:$[RANDOM%10]$[RANDOM%10]:$[RANDOM%10]$[RANDOM%10]
  register: random_mac_address
  changed_when: false

- name: set vm_mac variable
  set_fact:
    vm_mac: "{{ random_mac_address.stdout }}"

#- name: check for user provided static ip address info
#  set_fact:
#    static_ip: true
#  when:
#    - vm_mac is defined
#    - vm_ip is defined
#    - vm_gateway is defined
#    - vm_mask_prefix is defined

- name: generate {{ vm_name }} ifcfg interface template
  template:
    src: ifcfg.j2
    dest: "{{ vm_ifcfg }}"
  when: static_ip|bool

- name: Check if qcow OS image template exist
  stat:
    path: "{{ os_qcow_template }}"
  register: cloud_init_image_exist

- name: fail if {{ os_qcow_template }} does not exist
  fail:
    msg: |
         The qcow os template {{ os_qcow_template }} does not exist.
         Please verify the variable os_qcow_template is set to the correct path
         or copy {{ cloud_init_vm_image }} to {{ os_qcow_template }}.
  when: cloud_init_image_exist.stat.exists == False

- name: Copy cloud-init user data
  template:
    src: user-data.j2
    dest: "{{ cloud_init_user_data }}"
    mode: 0777
  register: user_data_cloud_init

- name: Generate cloud-init meta data
  template:
    src: meta-data.j2
    dest: "{{ cloud_init_meta_data }}"
    mode: 0777
  register: meta_data_cloud_init

- name: Create operating system disk for vm
  command: "qemu-img create -f qcow2 {{ os_disk }} {{ vm_root_disk_size }}"
  args:
    creates: "{{ os_disk }}"
  register: os_disk_results
  when: vm_name not in all_instances.list_vms

- name: Verify operating system disk for vm exists
  stat:
    path: "{{ os_disk }}"
  register: os_disk_created

- name: get operating system disk virtual size
  shell: >
    qemu-img info "{{ os_disk }}" | awk '/disk size/ {print $3}'
  register: os_virtual_disk_size
  changed_when: false

- name: set os disk size to human readable format
  set_fact:
    os_disk_size: "{{ os_virtual_disk_size.stdout | human_to_bytes }}"
  when: os_disk_created.stat.exists

- name: Push base image onto vm operating system disk
  command: >
    virt-resize --expand /dev/sda1 "{{ os_qcow_template }}" "{{ os_disk }}"
  register: resize_os_disk_results
  changed_when: '"Resize operation completed with no errors" in resize_os_disk_results.stdout'
  when: os_disk_created.stat.exists and os_disk_size|int < '1073741824'|int

- name: Grow root file system to size of disk
  command: "virt-customize -a {{ os_disk }} --run-command 'xfs_growfs /'"
  register: grow_os_disk_results
  changed_when: '"Finishing off" in grow_os_disk_results.stdout'
  when: os_disk_created.stat.exists and os_disk_size|int < '1073741824'|int

- name: Set the root password for the vm
  command: >
    virt-customize -a {{ os_disk }} --root-password password:{{ kvm_vm_root_pwd }}
  register: mod_os_disk_results
  changed_when: '"Finishing off" in mod_os_disk_results.stdout'
  when: grow_os_disk_results.changed

- name: check for existing cloud init iso
  stat:
    path: "{{ cloud_init_iso_image }}"
  register: cloud_init_iso

- name: Create iso image for cloud init
  shell: "genisoimage -input-charset utf-8 -output {{ cloud_init_iso_image }} -volid cidata -joliet -r {{ cloud_init_user_data }} {{ cloud_init_meta_data }}"
  when: user_data_cloud_init.changed or cloud_init_iso.stat.exists == False

- name: generate virt-install command arguments
  template:
    src: virt-install-cmd.j2
    dest: "{{ vm_virtinstall_script }}"
    mode: 0755
  when: vm_name not in all_instances.list_vms

- name: deploy VM instance
  command: "bash -x {{ vm_virtinstall_script }}"
  when: vm_name not in all_instances.list_vms
  register: deploy_vm
  failed_when: "('Domain installation does not' in deploy_vm.stderr) or
                ('failed to' in deploy_vm.stderr) or
                ('ERROR' in deploy_vm.stderr)"
- debug:
    msg: "{{ deploy_vm }}"
    verbosity: 2

- name: create extra qcow disk
  vars:
    disk_name: "{{ extra_disk_name }}_vd{{ disk_sequence[item | int + count ] }}.qcow2"
  command: >
    dd if=/dev/zero of={{ disk_name }} bs=1 count=0  seek={{ item.size }}
  args:
    creates: "{{ disk_name }}"
  loop: "{{ extra_storage }}"
  loop_control:
    index_var: count
    label: "{{ disk_name }}"
  when: item.enable
  register: extra_disk_created

- debug:
    msg: "{{ extra_disk_created }}"
    verbosity: 2

- name: Attach External Disk
  vars:
    disk_name: "{{ extra_disk_name }}_vd{{ disk_sequence[item | int + count ] }}.qcow2"
    disk: "vd{{ disk_sequence[item | int + count ] }}"
  command: >
    /usr/local/bin/attach-libvirt-disk "{{ vm_name }}" "{{ disk_name }}" "{{ disk }}"
  register: attached_disk
  loop: "{{ extra_storage }}"
  loop_control:
    index_var: count
    label: "{{ disk_name }}"
  when: item.enable
  changed_when: '"Disk attached successfully" in attached_disk.stdout'

- name: Check if cd-rom is attached
  shell: >
    virsh domblklist "{{ vm_name }}" | grep "{{ cidata_iso_name }}"|cat
  register: check_cdrom
  changed_when: false

- name: wait for cloud-init to initialize
  pause:
    seconds: 30
  when: vm_name not in all_instances.list_vms

- name: Eject CD-Rom
  shell: "virsh change-media {{ vm_name }} {{ check_cdrom.stdout.split()[0] }} --eject"
  when: check_cdrom.stdout != ""
