---
# tasks file for ansible-role-rhel7-kvm-cloud-init
- name: convert disk size to bytes
  vars:
    new_size: "{{ vm_root_disk_size }} GB"
    wanted_size: "{{ new_size|human_to_bytes }}"
  set_fact:
    expand_os_disk: "{{ true if wanted_size|int > '1073741824'|int else false }}"

- name: Get a list of all instances
  virt:
    command: list_vms
  register: all_instances
  become: yes
  tags: always

- name: check if networking should be static or dhcp
  set_fact:
    static_net: yes
  when: convert_dhcp_to_static|bool or vm_ipaddress != ""

- name: run tasks to teardown the VM
  import_tasks: teardown-vm.yml
  become: yes
  when: vm_teardown|bool

- name: Deploy the VM
  when: not vm_teardown|bool
  become: yes
  block:
    - name: INCLUDE TASKS from build_vm_config.yml to build the VM deployment config
      import_tasks: build_vm_config.yml
      
    - name: INCLUDE TASKS from deploy_vm.yml to deploy the vm
      import_tasks: deploy_vm.yml

    - name: INCLUDE TASKS from configure_vm.yml to configure the vm
      import_tasks: configure_vm.yml
    
- name: Refresh inventory to ensure new instances exist in inventory
  meta: refresh_inventory
    
- name: run post configuration
  when: not vm_teardown|bool
  import_tasks: post_config.yml
  become: yes
