---
# tasks file for ansible-role-rhel7-kvm-cloud-init

- name: copy scripts to KVM host
  copy:
    src: "files/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 755
    owner: root
  with_items:
    - getvmip
    - attach-libvirt-disk
  delegate_to: "{{ kvm_install_host }}"

- name: Get a list of all instances
  virt:
    command: list_vms
  register: all_instances
  become: yes
  delegate_to: "{{ kvm_install_host }}"

- name: run VM teardown tasks when vm_teardown
  import_tasks: teardown-vm.yml
  become: yes
  delegate_to: "{{ kvm_install_host }}"
  when: vm_teardown

- name: Create VM data dir to store vm information
  file:
    state: directory
    path: "{{ vm_data_dir }}/{{ vm_name }}"
    force: yes
  become: yes
  delegate_to: "{{ kvm_install_host }}"
  when: not vm_teardown

- name: Deploy Base VM
  import_tasks: deploy-vm.yml
  become: yes
  delegate_to: "{{ kvm_install_host }}"
  when: not vm_teardown

- name: Gather VM ip networking info
  import_tasks: get_ip_info.yml
  become: yes
  delegate_to: "{{ kvm_install_host }}"
  when: not vm_teardown

- name: add {{ vm_name }} to ansible inventory inventory
  lineinfile:
    path: "{{ inventory_file }}"
    regexp: "^{{ vm_name }}"
    line: "{{ vm_name }}   ansible_host={{ vm_ip }} ansible_user={{ admin_user }}"
    insertafter: '^\[{{ inventory_group }}\]'
    state: present
  register: vm_inventory_status
  when: update_inventory and vm_ip is defined

- name: refresh local static inventory
  meta: refresh_inventory

- name: ensure VM is using static ip address config
  import_tasks: dhcp_to_static.yml
  become: yes
  delegate_to: "{{ kvm_install_host }}"
  when: not vm_teardown and static_ip|bool

- name: run post configuration
  import_tasks: post-config.yml
  become: yes
